version: "2"
services:
  cups:
    # build: .
    image: nikoogle/cups-airprint:master
    container_name: cups
    network_mode: host
    restart: unless-stopped
    privileged: true #This might not be needed, correct me.
    volumes:
      - /var/run/dbus:/var/run/dbus
      - ./config:/config
      - ./services:/services
    devices:
      - /dev/bus:/dev/bus
      # - /dev/usb:/dev/usb
    environment:
      - CUPSADMIN=admin
      - CUPSPASSWORD=password
