name: Build Docker Image

on:
  push:
    branches: [ master, g1220-v1]
  pull_request:
    branches: [ master, g1220-v1]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Git checkout
        uses: actions/checkout@v1
      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}
      - name: Build the Docker image
        run: docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t nikoogle/cups-airprint:${GITHUB_REF##*/} --push .
